# Generated by Django 3.2.3 on 2021-05-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=250, null=True)),
                ('city', models.CharField(default='', max_length=1000, null=True)),
                ('state', models.CharField(default='', max_length=1000, null=True)),
                ('about', models.CharField(default='', max_length=1000, null=True)),
                ('status', models.CharField(default='', max_length=50, null=True)),
                ('user_created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
